version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  backend-image:
    image: backend-image:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ConnectionStrings:DatabaseContext: "Host=postgres_image;Port=5432;Username=admin;Password=password;Database=aoos"
    networks: 
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./dbscripts/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "aoos"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks: 
      - dockerapi-dev
    
volumes:
  dbscripts: