version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  backend-image:
    image: backend-image:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ConnectionStrings:DatabaseContext: "Host=postgres_image;Port=5433;Database=aoos;Username=admin;Password=pass"
    networks: 
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5433"
    restart: always
    volumes:
      - ./dbscripts/data_all.sql:/docker-entrypoint-initdb.d/data_all.sql
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "aoos"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
    - dockerapi-dev
    
volumes:
  dbscripts: